### ISSUE TITLE
[BUG] Videos can't be fullscreen

### ISSUE THREAD

**Issue by Tahinli** [Milkshiift/GoofCord#35] opened 2024-07-17 18:05 UTC
### Description
Videos in channels can't be watched in fullscreen

### Steps to Reproduce
Try to make a video fullscreen

### Expected Behavior
Being fullscreen

### Actual Behavior
Not being fullscreen

### Screenshots
:D

### Environment
Fedora 40 KDE Plasma
Software Version 1.5.0

**Comment by Milkshiift** [comment] 2024-07-17 18:07
Duplicate of https://github.com/Milkshiift/GoofCord/issues/32

**Closed by Milkshiift** 2024-07-17 18:07 UTC

**Comment by Tahinli** [comment] 2024-07-17 18:13
Is flatpak version updated ?

**Comment by Milkshiift** [comment] 2024-07-17 18:14
No, the update with the commit has not been released yet

**Comment by Tahinli** [comment] 2024-07-17 18:15
Thanks
