### ISSUE TITLE
[BUG] Reloading with Ctrl + R makes the client go into an infinite loading screen loop

### ISSUE THREAD

**Issue by Shavixinio** [Milkshiift/GoofCord#53] opened 2024-09-01 16:06 UTC
- [x] I have searched and found no existing issues on the same topic
- [x] I have searched the [wiki](https://github.com/Milkshiift/GoofCord/wiki/FAQ) and found no mention of my problem

### Description
When reloading the client, it is stuck in the loading screen until you close out of the client completely and relaunch it.
### Steps to Reproduce
1. Open Goofcord
2. Reload it with Ctrl + R
### Expected Behavior
The client should reload with no issues
### Actual Behavior
When the loading screen ends, it opens 2 more times, and the last time, it's stuck like this.
### Screenshots

https://github.com/user-attachments/assets/8904e0c2-11ac-4cf2-abd3-a1d753abc8de

### Environment
- Operating System (name and version): Windows 11 Pro
- GoofCord Version: 1.6.0
- Way of installing: [Through the x64 setup](https://github.com/Milkshiift/GoofCord/releases/download/v1.6.0/GoofCord.Setup.x64.exe)

**Comment by Wuemeli** [comment] 2024-09-13 17:43
@Shavixinio Are there any Errors in the Developer Console? Maybe with Client Mods or similiar?

**Comment by Milkshiift** [comment] 2024-09-13 17:45
This should be fixed in 1.7.0, actually. Not closing before @Shavixinio confirms it when the new version releases though

**Comment by Wuemeli** [comment] 2024-09-13 17:45
That's why I couldn't reproduce it

**Comment by Shavixinio** [comment] 2024-09-13 18:12
I will check it in a moment, let me boot up my PC.

**Comment by Shavixinio** [comment] 2024-09-13 18:18
I can still reproduce the bug. As for the console logs, I got this

![image](https://github.com/user-attachments/assets/1fe17d2d-0e31-489a-a6fd-77723e65354d)

After closing it entirely and opening GoofCord again, I got logged out of my account too for some reason

**Comment by Milkshiift** [comment] 2024-09-13 18:29
Thank you, but this should already be fixed upstream and therefore in the next version. I actually think it's fitting to close this, as I was able to reproduce the issue before the fix.

> After closing it entirely and opening GoofCord again, I got logged out of my account too for some reason

Discord does that when you open DevTools without a Vencord plugin to prevent it. Scam-protection™

**Closed by Milkshiift** 2024-09-13 18:29 UTC
