### ISSUE TITLE
[BUG] Cannot change input type to chewing(注音 specifically 小麥注音 mcbopomofo)

### ISSUE THREAD

**Issue by olivertzeng** [Milkshiift/GoofCord#49] opened 2024-08-22 14:28 UTC
- [x] I have searched and found no existing issues on the same topic
- [x] I have searched the [wiki](https://github.com/Milkshiift/GoofCord/wiki/FAQ) and found no mention of my problem

### Description
https://github.com/openvanilla/McBopomofo

### Steps to Reproduce
N/A

### Expected Behavior
when hitting shift or ctrl-space will change to bopomofo

### Actual Behavior
N/A

### Screenshots
N/A

### Environment
- Operating System (name and version):
- GoofCord Version: 1.6.0-1
- Way of installing: installing goofcord-bin from the [AUR](https://aur.archlinux.org/packages/goofcord-bin)

### Additional Information
https://github.com/openvanilla/McBopomofo
this is the input method source code

**Comment by Milkshiift** [comment] 2024-08-22 14:50
See https://github.com/Milkshiift/GoofCord/issues/24
Also, `Steps to Reproduce` is there for a reason. You can't just link a Chinese repo and expect me to know how it works or how you use it in your system. I'm not even sure if the linked issue applies because of lack of information. Like, are you using it with ibus? fcitx? And the repo you linked seems to be for macOS only...?

Closing this in favor of #24. If you think this needs to be a separate issue, let me know and provide more details.

**Closed by Milkshiift** 2024-08-22 14:50 UTC

**Comment by olivertzeng** [comment] 2024-08-22 14:56
> See #24 Also, `Steps to Reproduce` is there for a reason. You can't just link a Chinese repo and expect me to know how it works or how you use it in your system. I'm not even sure if the linked issue applies because of lack of information. Like, are you using it with ibus? fcitx? And the repo you linked seems to be for macOS only...?
> 
> Closing this in favor of #24. If you think this needs to be a separate issue, let me know and provide more details.

Sorry for not making myself clear :(
Firstly, for how to reproduce the issue(i somehow don't know why i just N/Aed that point :(), you just have mcbopomofo installed and then go on goofcord press ctrl+space or shift. Then the issue is produced!(the selection prompt doesn't appear)

Apparently for #24 as a dup I agree that my preferred Chinese input method mcbopomofo is kinda similar to ibus' functions, while not associated in any way. So it's kinda separate but not.(So no, I'm not using fcitx or ibus, I used to)

Hope that this clarifies, and sorry for the confusion.

**Comment by Milkshiift** [comment] 2024-08-22 15:11
So, if not ibus or fcitx, you are using SCIM? https://en.wikipedia.org/wiki/Smart_Common_Input_Method
What really matters here is input framework, not input method (McBopomofo)

**Comment by Milkshiift** [comment] 2024-08-22 15:13
Also try running GoofCord with an `--ozone-platform-hint=x11` argument. If it fixes the problem, then this is still a duplicate of #24 and everything (?) there applies to your problem too

**Comment by olivertzeng** [comment] 2024-08-22 15:15
> So, if not ibus or fcitx, you are using SCIM? [en.wikipedia.org/wiki/Smart_Common_Input_Method](https://en.wikipedia.org/wiki/Smart_Common_Input_Method) What really matters here is input framework, not input method (McBopomofo)

i didn't know that! It seems like that is using fcitx5 so i think it's prob a dup

oh yeah im on wayland

**Comment by olivertzeng** [comment] 2024-08-22 15:19
> Also try running GoofCord with an `--ozone-platform-hint=x11` argument. If it fixes the problem, then this is still a duplicate of #24 and everything (?) there applies to your problem too

it didn't work

**Comment by olivertzeng** [comment] 2024-08-22 15:34
> Weird. Maybe try `--ozone-platform=x11` or `env -u WAYLAND_DISPLAY goofcord`

nice the former works!
but the weird thing is after running that it works every time i open

**Comment by Milkshiift** [comment] 2024-08-22 15:36
Even without the argument? :sparkles: magic :sparkles: I guess.
Glad it works for you

**Comment by olivertzeng** [comment] 2024-08-22 15:39
> Even without the argument? ✨ magic ✨ I guess. Glad it works for you

:)
this is done by pure magic
ill maybe come back to this thread if i have any problems about this in the future
maybe you could change this thread from not planned to completed 💯

**Comment by Milkshiift** [comment] 2024-08-22 15:43
It would be better to continue discussion if needed here https://github.com/Milkshiift/GoofCord/issues/24
`--ozone-platform=x11` makes GoofCord run in XWayland mode, which is more of a workaround, so "not planned" seems to be more fitting.

**Comment by olivertzeng** [comment] 2024-08-22 15:45
> It would be better to continue discussion if needed here https://github.com/Milkshiift/GoofCord/issues/24
> 
> `--ozone-platform=x11` makes GoofCord run in XWayland mode, which is more of a workaround, so "not planned" seems to be more fitting.

Wait I just discovered that goofcord without arguments works out of the box but

Running the desktop app doesn't work

**Comment by Milkshiift** [comment] 2024-08-22 15:51
Oh yeah the AUR package doesn't run in native Wayland mode by default. I don't know why your desktop entry has `--ozone-platform-hint=auto` (to run natively) though. You can remove the argument from it if you need to

**Comment by olivertzeng** [comment] 2024-08-23 00:43
> Oh yeah the AUR package doesn't run in native Wayland mode by default. I don't know why your desktop entry has `--ozone-platform-hint=auto` (to run natively) though. You can remove the argument from it if you need to

alright just checked out the desktop file in /usr/share/applications/goofcord.desktop
I've changed it to this:
```
[Desktop Entry]
Name=GoofCord
Exec=goofcord --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=x11 %U
Terminal=false
Type=Application
Icon=goofcord
StartupWMClass=GoofCord
Comment=Take control of your Discord experience with GoofCord – the highly configurable and privacy-minded discord client.
Categories=Network;
```
the Exec command `goofcord --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=x11` works but the desktop app doesn't. weird

**Comment by olivertzeng** [comment] 2024-08-27 11:14
> Oh yeah the AUR package doesn't run in native Wayland mode by default. I don't know why your desktop entry has `--ozone-platform-hint=auto` (to run natively) though. You can remove the argument from it if you need to

Since I need to run `goofcord` every time I open it can I daemonize it?

**Comment by Milkshiift** [comment] 2024-08-27 11:23
[Yes](https://superuser.com/questions/178587/how-do-i-detach-a-process-from-terminal-entirely). `goofcord &; disown` does it for me

**Comment by olivertzeng** [comment] 2024-08-27 11:25
Nice lemme tryMessage ID: ***@***.***&gt;
